# fly.toml app configuration file generated for parroteer-reflector on 2026-04-20T23:20:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'parroteer-reflector'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'


[[services]]
  protocol = 'tcp'
  internal_port = 80

  [[services.ports]]
    port = 80

[[services]]
  protocol = 'tcp'
  internal_port = 443

  [[services.ports]]
    port = 443

[[services]]
  protocol = 'udp'
  internal_port = 443

  [[services.ports]]
    port = 443

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256
